# Torch安装测试

In [6]:
import torch
torch.__version__

'2.11.0+cu130'

In [8]:
torch.cuda.is_available()

False

In [9]:
torch.backends.mps.is_available()

False

# Tensor 张量测试

In [1]:
import torch

In [14]:
tensor0d = torch.tensor(1)
print(tensor0d.shape, tensor0d.dtype)

torch.Size([]) torch.int64


In [15]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.shape, tensor1d.dtype)

torch.Size([3]) torch.int64


In [18]:
tensor2d = torch.tensor([[1, 2, 3], [4., 5., 6.]])
print(tensor2d.shape, tensor2d.dtype)

torch.Size([2, 3]) torch.float32


In [4]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d.shape, tensor3d.dtype)

float3d = tensor3d.to(torch.float32)
print(float3d.shape, float3d.dtype)

torch.Size([2, 2, 2]) torch.int64
torch.Size([2, 2, 2]) torch.float32


In [ ]:
x = tensor3d.stride()
print(x)

# (4, 2, 1)
# 跳到下一块，需要跨4个数；跳到下一行，需要跨2个数；跳到下一列，需要跨1个数。

(4, 2, 1)


In [20]:
float2d = torch.tensor([[1, 2, 3], [4., 5., 6.]], dtype=torch.float32)
print(float2d.shape, float2d.dtype)

torch.Size([2, 3]) torch.float32


In [21]:
float64 = torch.tensor([[1, 2, 3], [4., 5., 6.]], dtype=torch.float64)
print(float64.shape, float64.dtype)

torch.Size([2, 3]) torch.float64


# Tensor 重塑

In [5]:
import torch

In [10]:
tensor2d = torch.tensor([[1, 2, 3], [7, 8, 9]], dtype=torch.float32)
print(tensor2d.shape, tensor2d.dtype)
print(tensor2d)

torch.Size([2, 3]) torch.float32
tensor([[1., 2., 3.],
        [7., 8., 9.]])


In [11]:
view2d = tensor2d.view(3, 2)
print(view2d.shape, view2d.dtype)
print(view2d)

torch.Size([3, 2]) torch.float32
tensor([[1., 2.],
        [3., 7.],
        [8., 9.]])


In [12]:
reshape2d = tensor2d.reshape(3, 2)
print(reshape2d.shape, reshape2d.dtype)
print(reshape2d)

torch.Size([3, 2]) torch.float32
tensor([[1., 2.],
        [3., 7.],
        [8., 9.]])


## 张量转置

In [13]:
tensor2T = tensor2d.T
print(tensor2T.shape, tensor2T.dtype)
print(tensor2T)

torch.Size([3, 2]) torch.float32
tensor([[1., 7.],
        [2., 8.],
        [3., 9.]])


## 张量相乘

In [15]:
print(tensor2d)
print(tensor2T)

matmul2d = tensor2d @ tensor2T
print(matmul2d.shape, matmul2d.dtype)
print(matmul2d)

matmul2d_2 = torch.matmul(tensor2d, tensor2T)
print(matmul2d_2.shape, matmul2d_2.dtype)
print(matmul2d_2)

tensor([[1., 2., 3.],
        [7., 8., 9.]])
tensor([[1., 7.],
        [2., 8.],
        [3., 9.]])
torch.Size([2, 2]) torch.float32
tensor([[ 14.,  50.],
        [ 50., 194.]])
torch.Size([2, 2]) torch.float32
tensor([[ 14.,  50.],
        [ 50., 194.]])
